# FROM nginx:1.13

# COPY /Config /etc/nginx
# COPY /Content /usr/share/nginx/html

FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
#RUN rm /etc/nginx/conf.d/examplessl.conf
COPY Content /usr/share/nginx/html
COPY Content /var/www/html
COPY Config /etc/nginx